from __future__ import annotations

from agent.motor.backends import MotorBackend, NullBackend, PyAutoGUIBackend
from agent.motor.controller import MotorController
from agent.motor.result import ActionResult
from agent.motor.spec import (
    ACTION_ADAPTER,
    ActionSpec,
    ClickAction,
    DoubleClickAction,
    DragAction,
    HotkeyAction,
    MoveAction,
    PressAction,
    RightClickAction,
    ScreenshotAction,
    ScrollAction,
    TypeAction,
    WaitAction,
    action_coord,
    action_payload_text,
    click,
    double_click,
    drag_to,
    hotkey,
    move_to,
    parse_action,
    press,
    right_click,
    screenshot,
    scroll,
    spec_from_kind,
    type_text,
    wait,
)

__all__ = [
    "ACTION_ADAPTER",
    "ActionResult",
    "ActionSpec",
    "ClickAction",
    "DoubleClickAction",
    "DragAction",
    "HotkeyAction",
    "MotorBackend",
    "MotorController",
    "MoveAction",
    "NullBackend",
    "PressAction",
    "PyAutoGUIBackend",
    "RightClickAction",
    "ScreenshotAction",
    "ScrollAction",
    "TypeAction",
    "WaitAction",
    "action_coord",
    "action_payload_text",
    "click",
    "double_click",
    "drag_to",
    "hotkey",
    "move_to",
    "parse_action",
    "press",
    "right_click",
    "screenshot",
    "scroll",
    "spec_from_kind",
    "type_text",
    "wait",
]
