"""Contracts between the gateway and the rest of STAR 2.0.

The gateway must not import the brain/orchestrator directly (that would couple the
transport to the reasoning layers). It talks to this protocol instead, so the
application object can grow phase by phase without any route ever changing.
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

__all__ = ["StarApplicationProtocol"]


@runtime_checkable
class StarApplicationProtocol(Protocol):
    """Everything the HTTP/WS surface is allowed to ask the Star brain for."""

    # ── introspection ───────────────────────────────────────────────────────
    def info(self) -> dict[str, Any]: ...

    def health(self) -> dict[str, Any]: ...

    def status(self) -> dict[str, Any]: ...

    def agents(self) -> list[dict[str, Any]]: ...

    def tools(self) -> list[dict[str, Any]]: ...

    def tasks(self, *, limit: int = 50) -> list[dict[str, Any]]: ...

    def plans(self, *, limit: int = 20) -> list[dict[str, Any]]: ...

    def workspaces(self) -> list[dict[str, Any]]: ...

    def workspace_state(self) -> dict[str, Any]: ...

    def workspace_session(self, session_id: str) -> dict[str, Any]: ...

    async def create_workspace(self, kind: str = "generic", label: str = "", ttl_s: float | None = None, *, dry_run: bool | None = None) -> dict[str, Any]: ...

    async def close_workspace(self, session_id: str, *, destroy: bool = False, dry_run: bool | None = None) -> dict[str, Any]: ...

    async def checkpoint_workspace(self, session_id: str = "", label: str = "", *, dry_run: bool | None = None) -> dict[str, Any]: ...

    async def restore_workspace(self, session_id: str = "", checkpoint_id: str = "", *, dry_run: bool | None = None) -> dict[str, Any]: ...

    def confirmations(self) -> list[dict[str, Any]]: ...

    def memory_snapshot(self, query: str | None = None, *, limit: int = 20) -> dict[str, Any]: ...

    def learning_snapshot(self, *, limit: int = 50) -> dict[str, Any]: ...

    def learning_feedback(self, **kwargs: Any) -> dict[str, Any]: ...

    def learning_cycle(self, **kwargs: Any) -> dict[str, Any]: ...

    def audit_tail(self, *, limit: int = 50) -> list[dict[str, Any]]: ...

    def browser_state(self) -> dict[str, Any]: ...

    def computer_state(self) -> dict[str, Any]: ...

    def event_history(
        self, *, limit: int = 50, kinds: frozenset[str] | None = None, since_seq: int = 0
    ) -> list[dict[str, Any]]: ...

    # ── actions ─────────────────────────────────────────────────────────────
    async def chat(
        self,
        text: str,
        *,
        session_id: str | None = None,
        language: str | None = None,
        source: str = "text",
    ) -> dict[str, Any]: ...

    async def handle_message(self, message: dict[str, Any]) -> dict[str, Any]: ...

    async def resolve_confirmation(self, confirmation_id: str, *, approve: bool, note: str = "") -> dict[str, Any]: ...

    async def cancel_task(self, task_id: str) -> dict[str, Any]: ...

    async def run_browser_goal(self, goal: str, *, session_id: str = "", dry_run: bool | None = None) -> dict[str, Any]: ...

    async def run_computer_goal(self, goal: str, *, session_id: str = "", dry_run: bool | None = None) -> dict[str, Any]: ...

    async def emergency_stop(self, *, reason: str = "user") -> dict[str, Any]: ...

    async def remember(self, text: str, *, kind: str = "fact", key: str | None = None, value: str | None = None) -> dict[str, Any]: ...

    async def aclose(self) -> None: ...
